name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

# explicitly configure permissions, in case your GITHUB_TOKEN workflow permissions are set to read-only in repository settings
permissions:
  actions: write
  contents: read # read-only since signatures are stored in remote repository
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.CLA_APP_ID }}
          private-key: ${{ secrets.CLA_APP_PRIVATE_KEY }}
          owner: nxm-rs
          repositories: "nexum,cla-signatures"

      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          path-to-signatures: 'nexum/cla.json'
          path-to-document: 'https://github.com/nxm-rs/nexum/blob/main/CLA.md'
          # branch should not be protected
          branch: 'main'
          remote-organization-name: 'nxm-rs'
          remote-repository-name: 'cla-signatures'
