name: Lint, build, test

# run this action on main branch and every pull request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code

        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@5b842231ba77f5c045dba54ac5560fed2db780e2  # nightly
        with:
          toolchain: nightly-2026-04-07
          targets: wasm32-unknown-unknown,x86_64-unknown-linux-gnu
          components: clippy,rustfmt

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae  # v5.0.5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-binstall
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install trunk and just
        run: cargo binstall trunk just

      - name: Install needed packages
        run: sudo apt install -y libpcsclite-dev

      - name: Cargo fmt
        run: cargo fmt --all -- --check

      - name: Cargo clippy
        run: just clippy

      - name: Cargo build
        run: just build

      - name: Cargo build extension
        run: just be

      - name: Upload firefox extension
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: firefox-extension
          path: crates/nexum/extension/dist/
