name: Lint, build, test

# run this action on main branch and every pull request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code

        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1

      - name: Install Rust
        uses: dtolnay/rust-toolchain@5b842231ba77f5c045dba54ac5560fed2db780e2  # nightly
        with:
          toolchain: nightly-2026-04-07
          targets: wasm32-unknown-unknown,x86_64-unknown-linux-gnu
          components: clippy,rustfmt

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830  # v4.3.0
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-binstall
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install trunk and just
        run: cargo binstall trunk just

      - name: Install needed packages
        run: sudo apt install -y libpcsclite-dev

      - name: Cargo fmt
        run: cargo fmt --all -- --check

      - name: Cargo clippy
        run: just clippy

      - name: Cargo build
        run: just build

      - name: Cargo build extension
        run: just be

      - name: Upload firefox extension
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        with:
          name: firefox-extension
          path: crates/nexum/extension/dist/
